
DROP TABLE IF EXISTS enrollment;
DROP TABLE IF EXISTS class;
DROP TABLE IF EXISTS course;
DROP TABLE IF EXISTS student;
DROP TABLE IF EXISTS instructor;


CREATE TABLE instructor (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL
);

CREATE TABLE student (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL
);

CREATE TABLE course (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL
);

CREATE TABLE class (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  course_id INTEGER NOT NULL,
  instructor_id INTEGER,
  start_date DATE,
  end_date DATE,
  FOREIGN KEY (course_id) REFERENCES course(id) ON DELETE CASCADE,
  FOREIGN KEY (instructor_id) REFERENCES instructor(id) ON DELETE SET NULL
);

CREATE TABLE enrollment (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  class_id INTEGER NOT NULL,
  student_id INTEGER NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT NOW(),
  FOREIGN KEY (class_id) REFERENCES class(id) ON DELETE CASCADE,
  FOREIGN KEY (student_id) REFERENCES student(id) ON DELETE CASCADE
);
